# Generated by Django 5.2.7 on 2025-10-15 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("investments", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("total_rentals", models.IntegerField(default=0)),
                ("client_satisfaction", models.FloatField(default=0.0)),
                ("response_time", models.FloatField(default=0.0)),
                ("ranking_score", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="agents.agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestmentTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trend_type",
                    models.CharField(
                        choices=[
                            ("growth", "Growth"),
                            ("decline", "Decline"),
                            ("stable", "Stable"),
                        ],
                        default="stable",
                        max_length=50,
                    ),
                ),
                ("roi_percentage", models.FloatField(default=0.0)),
                ("trend_date", models.DateTimeField(auto_now_add=True)),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trends",
                        to="investments.investment",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("inquiries", models.PositiveIntegerField(default=0)),
                ("favorites", models.PositiveIntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="properties.property",
                    ),
                ),
            ],
        ),
    ]
